var cart = new Vue({
  el:'#cart',
    data:{
      itemList:[
      {
        id:'1',
        itemName:'一般禮盒(小)',
        imgUrl:'backet1.png',
        price:'120',
        count:'1'
      },
      {
        id:'2',
        itemName:'水果禮盒',
        imgUrl:'fruitsbacket2.png',
        price:'150',
        count:'1'
      },
      {
        id:'3',
        itemName:'一般禮盒(中)',
        imgUrl:'backet3.png',
        price:'150',
        count:'1'
      },
      {
        id:'4',
        itemName:'有機禮盒',
        imgUrl:'organicbacket4.png',
        price:'175',
        count:'1'
      },
      {
        id:'5',
        itemName:'一般禮盒(大)',
        imgUrl:'backet5.png',
        price:'200',
        count:'1'
      },
      ]
      },
    methods:{
      Plus: function(item){
        item.count++;
      },
      Sub: function(item){
        if(item.count>1){
          item.count--;                
        }
      },
      computed:{
      }
    }
})