var cart = new Vue({
  el:'#cart',
    data:{
      itemList:[
      {
        id:'1',
        itemName:'蘋果',
        imgUrl:'apple.png',
        price:'45',
        count:'1'
      },
      {
        id:'2',
        itemName:'藍莓',
        imgUrl:'blueberry.png',
        price:'40',
        count:'1'
      },
      {
        id:'3',
        itemName:'火龍果',
        imgUrl:'dragon-fruit.png',
        price:'40',
        count:'1'
      },
      {
        id:'4',
        itemName:'葡萄',
        imgUrl:'grapes.png',
        price:'60',
        count:'1'
      },
      {
        id:'5',
        itemName:'芭樂',
        imgUrl:'guava.png',
        price:'25',
        count:'1'
      },
      {
        id:'6',
        itemName:'奇異果',
        imgUrl:'kiwi.png',
        price:'40',
        count:'1'
      },
      {
        id:'7',
        itemName:'橘子',
        imgUrl:'orange-juice.png',
        price:'20',
        count:'1'
      },
      {
        id:'8',
        itemName:'木瓜',
        imgUrl:'papaya.png',
        price:'40',
        count:'1'
      },
      {
        id:'9',
        itemName:'楊桃',
        imgUrl:'star-fruit.png',
        price:'40',
        count:'1'
      },
      {
        id:'10',
        itemName:'草莓',
        imgUrl:'strawberry.png',
        price:'50',
        count:'1'
      },
      {
        id:'11',
        itemName:'番茄',
        imgUrl:'tomato.png',
        price:'25',
        count:'1'
      },
      {
        id:'12',
        itemName:'香蕉',
        imgUrl:'bananas.png',
        price:'25',
        count:'1'
      },
      {
        id:'13',
        itemName:'南瓜',
        imgUrl:'pumkin.png',
        price:'45',
        count:'1'
      },

      ]
      },
    methods:{
      Plus: function(item){
        item.count++;
      },
      Sub: function(item){
        if(item.count>1){
          item.count--;                
        }
      },
      computed:{
      }
    }
})