var cart = new Vue({
  el:'#cart',
    data:{
      itemList:[
      {
        id:'1',
        itemName:'高麗菜',
        imgUrl:'cabbage.png',
        price:'75',
        count:'1'
      },
      {
        id:'2',
        itemName:'萵苣',
        imgUrl:'lettuce.png',
        price:'30',
        count:'1'
      },
      {
        id:'3',
        itemName:'甘藍菜',
        imgUrl:'salad.png',
        price:'30',
        count:'1'
      },
      {
        id:'4',
        itemName:'菠菜',
        imgUrl:'spinach.png',
        price:'35',
        count:'1'
      },
      {
        id:'5',
        itemName:'青花菜',
        imgUrl:'broccoli.png',
        price:'45',
        count:'1'
      },
      {
        id:'6',
        itemName:'白花菜',
        imgUrl:'cauliflower.png',
        price:'45',
        count:'1'
      },
      ]
      },
    methods:{
      Plus: function(item){
        item.count++;
      },
      Sub: function(item){
        if(item.count>1){
          item.count--;                
        }
      },
      computed:{
      }
    }
})