var cart = new Vue({
  el:'#cart',
    data:{
      itemList:[
      {
        id:'1',
        itemName:'香菇',
        imgUrl:'mushroom.png',
        price:'60',
        count:'1'
      },
      {
        id:'2',
        itemName:'鴻喜菇',
        imgUrl:'Hongxi.png',
        price:'50',
        count:'1'
      },
      {
        id:'3',
        itemName:'金針菇',
        imgUrl:'enoki.png',
        price:'20',
        count:'1'
      },
      ]
      },
    methods:{
      Plus: function(item){
        item.count++;
      },
      Sub: function(item){
        if(item.count>1){
          item.count--;                
        }
      },
      computed:{
      }
    }
})