var cart = new Vue({
  el:'#cart',
    data:{
      itemList:[
      {
        id:'1',
        itemName:'紅蘿蔔',
        imgUrl:'carrot.png',
        price:'30',
        count:'1'
      },
      {
        id:'2',
        itemName:'白蘿蔔',
        imgUrl:'radish.png',
        price:'30',
        count:'1'
      },
      {
        id:'3',
        itemName:'大頭菜',
        imgUrl:'kohlrabi.png',
        price:'30',
        count:'1'
      },
      {
        id:'4',
        itemName:'番薯',
        imgUrl:'sweet-potato.png',
        price:'20',
        count:'1'
      },
      {
        id:'5',
        itemName:'馬鈴薯',
        imgUrl:'potato.png',
        price:'35',
        count:'1'
      },
      {
        id:'5',
        itemName:'薑',
        imgUrl:'ginger.png',
        price:'25',
        count:'1'
      },
      {
        id:'5',
        itemName:'甜菜根',
        imgUrl:'beet.png',
        price:'25',
        count:'1'
      },
      ]
      },
    methods:{
      Plus: function(item){
        item.count++;
      },
      Sub: function(item){
        if(item.count>1){
          item.count--;                
        }
      },
      computed:{
      }
    }
})